# -*- coding: utf-8 -*-
"""dan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0TT_qW-loal9qDDgp4z5PUKtiQRYBR6
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

data={
    'Roll':[11,18,20,22,24,26,28,30],
    'Age':[12,13,14,11,32,22,32,41],
    'Mark':[90,88,99,45,35,65,77,56]
}

df = pd.DataFrame(data)

df #table

df.head() #1st 5

df.tail() #last 5

df.columns #1stcol alone

df.shape #rows,col

df.info() #null,datatyp

df=pd.DataFrame(data)

df.describe() #static value

"""Scatter Plot"""

plt.figure(figsize=(10,2))
plt.scatter(df['Roll'],df['Age'])
plt.title("class vs student")
plt.xlabel("Age")
plt.ylabel("Roll")
plt.grid(True)
plt.show()

plt.figure(figsize=(10,2))
plt.plot(df['Roll'],df['Age'],marker=0)
plt.title("class vs student")
plt.xlabel("Age")
plt.ylabel("Roll")
plt.grid(True)
plt.show()

plt.figure(figsize=(10,2))
plt.bar(df['Roll'],df['Age'])
plt.title("class vs student")
plt.xlabel("Age")
plt.ylabel("Roll")
plt.grid(True)
plt.show()

plt.figure(figsize=(10,2))
plt.hist(df['Age'],bins=6)
plt.title("class vs stude,nt")
plt.xlabel("Age")
plt.ylabel("Roll")
plt.grid(True)
plt.show()

plt.figure(figsize=(10,2))
plt.boxplot(df['Age'])
plt.title("class vs student")
plt.grid(True)
plt.show()